import { pgTable, text, timestamp, uuid, pgEnum, integer, boolean } from 'drizzle-orm/pg-core';
import { users } from './users';
import { competitions } from './competitions';

// Achievement types enum
export const achievementTypeEnum = pgEnum('achievement_type', [
    'first_trade',
    'profit_10',
    'profit_25',
    'profit_50',
    'profit_100',
    'diamond_hands',
    'day_trader',
    'diversified',
    'market_master',
    'early_bird',
    'night_owl',
    'comeback_king',
    'winning_streak',
    'volume_trader',
    'top_10',
    'top_3',
    'champion',
]);

// Achievement definitions (metadata)
export const achievementDefinitions = pgTable('achievement_definitions', {
    id: text('id').primaryKey(), // Same as achievement_type value
    name: text('name').notNull(),
    description: text('description').notNull(),
    icon: text('icon').notNull(), // Emoji or icon name
    category: text('category').notNull(), // 'trading', 'profit', 'milestone', 'special'
    points: integer('points').default(10).notNull(),
    rarity: text('rarity').default('common').notNull(), // 'common', 'uncommon', 'rare', 'epic', 'legendary'
    isSecret: boolean('is_secret').default(false).notNull(),
    createdAt: timestamp('created_at').defaultNow().notNull(),
});

// User achievements (earned badges)
export const userAchievements = pgTable('user_achievements', {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
    competitionId: uuid('competition_id').references(() => competitions.id, { onDelete: 'cascade' }),
    achievementId: text('achievement_id').notNull().references(() => achievementDefinitions.id),
    earnedAt: timestamp('earned_at').defaultNow().notNull(),
    metadata: text('metadata'), // JSON string with extra data (e.g., profit percentage, streak count)
});

// Default achievement definitions to seed
export const DEFAULT_ACHIEVEMENTS = [
    {
        id: 'first_trade',
        name: 'First Trade',
        description: 'Complete your first trade',
        icon: '🎯',
        category: 'milestone',
        points: 10,
        rarity: 'common',
        isSecret: false,
    },
    {
        id: 'profit_10',
        name: 'Rising Star',
        description: 'Achieve 10% portfolio profit',
        icon: '⭐',
        category: 'profit',
        points: 25,
        rarity: 'common',
        isSecret: false,
    },
    {
        id: 'profit_25',
        name: 'Profit Pro',
        description: 'Achieve 25% portfolio profit',
        icon: '💫',
        category: 'profit',
        points: 50,
        rarity: 'uncommon',
        isSecret: false,
    },
    {
        id: 'profit_50',
        name: 'Market Wizard',
        description: 'Achieve 50% portfolio profit',
        icon: '🧙',
        category: 'profit',
        points: 100,
        rarity: 'rare',
        isSecret: false,
    },
    {
        id: 'profit_100',
        name: 'Legend',
        description: 'Double your portfolio (100% profit)',
        icon: '👑',
        category: 'profit',
        points: 250,
        rarity: 'legendary',
        isSecret: false,
    },
    {
        id: 'diamond_hands',
        name: 'Diamond Hands',
        description: 'Hold a position through 20% drawdown without selling',
        icon: '💎',
        category: 'trading',
        points: 50,
        rarity: 'rare',
        isSecret: false,
    },
    {
        id: 'day_trader',
        name: 'Day Trader',
        description: 'Complete 10 trades in a single day',
        icon: '📊',
        category: 'trading',
        points: 30,
        rarity: 'uncommon',
        isSecret: false,
    },
    {
        id: 'diversified',
        name: 'Diversified',
        description: 'Hold positions in 5 or more different stocks',
        icon: '🌈',
        category: 'trading',
        points: 20,
        rarity: 'common',
        isSecret: false,
    },
    {
        id: 'market_master',
        name: 'Market Master',
        description: 'Trade every stock in the market at least once',
        icon: '🏆',
        category: 'milestone',
        points: 100,
        rarity: 'epic',
        isSecret: false,
    },
    {
        id: 'early_bird',
        name: 'Early Bird',
        description: 'Make a trade within the first hour of competition',
        icon: '🐦',
        category: 'special',
        points: 15,
        rarity: 'uncommon',
        isSecret: false,
    },
    {
        id: 'comeback_king',
        name: 'Comeback King',
        description: 'Recover from a 15% loss to profit',
        icon: '🦁',
        category: 'special',
        points: 75,
        rarity: 'rare',
        isSecret: true,
    },
    {
        id: 'winning_streak',
        name: 'Winning Streak',
        description: 'Make 5 profitable trades in a row',
        icon: '🔥',
        category: 'trading',
        points: 40,
        rarity: 'uncommon',
        isSecret: false,
    },
    {
        id: 'volume_trader',
        name: 'Volume Trader',
        description: 'Trade over Rs. 10,00,000 in total volume',
        icon: '📈',
        category: 'milestone',
        points: 50,
        rarity: 'rare',
        isSecret: false,
    },
    {
        id: 'top_10',
        name: 'Top 10',
        description: 'Finish in the top 10 of a competition',
        icon: '🥉',
        category: 'milestone',
        points: 100,
        rarity: 'epic',
        isSecret: false,
    },
    {
        id: 'top_3',
        name: 'Podium Finish',
        description: 'Finish in the top 3 of a competition',
        icon: '🥈',
        category: 'milestone',
        points: 200,
        rarity: 'epic',
        isSecret: false,
    },
    {
        id: 'champion',
        name: 'Champion',
        description: 'Win a competition',
        icon: '🥇',
        category: 'milestone',
        points: 500,
        rarity: 'legendary',
        isSecret: false,
    },
];
